apiVersion: apps/v1
kind: Deployment
metadata:
  name: saludador
  labels:
    app: saludador
spec:
  replicas: 2
  selector:
    matchLabels:
      app: saludador
  template:
    metadata:
      labels:
        app: saludador
    spec:
      containers:
      - name: saludador
        image: tolengo/saludador:1.0
        ports:
        - containerPort: 80
